language: python
python:
- '2.7'
- '3.2'
- '3.3'
install: pip install . --use-mirrors
before_script: python setup.py testdep
script:
- python setup.py test
- python setup.py livetest
branches:
  only:
  - development
env:
  global:
  - secure: Gcwdd75RqfnUDV8A0ba/UWTGXLBCOUA5K9IUq7A7wijACAnfWxkOt1mrCvUQVYVmTjwvtoUzSYEUADP98dSENOhMJdulczcnsGdH8SfZxXIGIhfYK5Ukccq1MazK0Hh8TUJO/lwGyJS1o9hi/fBHt6MlTFz3c622Sc4nnYoxjiw=
  - secure: csnXLRA9AS4ByAxiZruhrJOtwcOpOqziOcR8Awg/vYJ+StGZUyIQPprKYF3JdwC9ehjum3SWvSLTIlRKN/SSH6k+1JIpxJmwshHJtgJnn93iDrMSV3nyWOzXnLd8cuDrbMfcHygnbhnwkj0lqdhr4kog43pKYzYnwTdBS/6bW14=
